name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}   
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}  

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository 
       uses: actions/checkout@v3
       
     - name: docker login
       uses: docker/login-action@v2
       with:
         username: ${{secrets.DOCKERHUB_USERNAME}}   
         password: ${{secrets.DOCKERHUB_TOKEN}}

      #run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag rocheandley/friday:$(date +%d)
       
     - name: Docker Push
       run: docker push rocheandley/friday:$(date +%d)
       
     - name: Deploy
       uses: appleboy/ssh-action@v0.1.7
       with: 
         host: ${{secrets.SSH_HOST}}
         key: ${{secrets.SSH_KEY}}
         username: ${{ secrets.SSH_USERNAME}}
         
         script: |
           whoami
           echo "Jullee owes me a house"
           docker pull rocheandley/friday:$(date +%d)
           docker stop friday
           
       
       
      
      

    

    
    
    
    
    
    

