name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}   
    - name: print name
      run: echo $DOCKER_USER
       
  #    run: | 
   #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the DOcker image
      run: docker build . --file Dockerfile --tag rocheandley/friday:$(date +%s_)
       
    - name: Docker Push
      run: docker push ${{secrets.DOCKER.USER}}/Friday
      
      

    

    
    
    
    
    
    

